bridge:
  ros__parameters:
    # topics and namespaces
    ego_namespace: 'ego_racecar'
    ego_scan_topic: 'scan'
    ego_odom_topic: 'odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'

    opp_namespace: 'opp_racecar'
    opp_scan_topic: 'opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: 'opp_drive'

    # transform related
    scan_distance_to_base_link: 0.275

    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # map parameters
    map_path: '/sim_ws/src/f1tenth_gym_ros/maps/korea_stress_obs'
    map_img_ext: '.png'

    # simulation agents (single-car mode)
    num_agent: 1

    # ego starting pose
    sx: 1.9216649
    sy: -6.5637771
    stheta: -3.0963021

    # opponent pose (unused when num_agent = 1)
    sx1: 0.0979211
    sy1: -5.9170505
    stheta1: -2.3942765

    kb_teleop: True
